### ISSUE TITLE
lock file maintenance

### ISSUE THREAD

**Issue by rarkins** [renovatebot/presets-internal#6]
Leaving lock file maintenance requiring approval will likely mean that our repos often have outdated lock files. Possibilities:

- Stop requiring approval: create PRs automatically once a week
- Branch automerge: create automatically and branch automerge if they pass

**Comment by viceice** [comment]
just used a copy of our main repo, will move to weekly auto maintanance

**Comment by viceice** [comment]
done in https://github.com/renovatebot/presets-internal/commit/ca1fc4666ab5d47b73908766889fea1d788ae031
