### ISSUE TITLE
Automerge not working for renovate/renovate docker docs PRs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/presets-internal#9]
We're using the following config for PR's like https://github.com/renovatebot/renovate/pull/8404:

https://github.com/renovatebot/presets-internal/blob/e76cbe38d937e097ae279c4b5e3c6ff6097d21e5/base.json#L65-L76

Automerge is set to `true`, but the PR body still says:
> 🚦 Automerge: Disabled by config. Please merge this manually once you are satisfied.

So we're doing _something_ wrong here... 😄 
Unfortunately, I don't know what we should be doing here...
Somebody smarter than me will have to take a look at this. 😄

**Comment by rarkins** [comment]
It's perhaps this rule: https://github.com/renovatebot/renovate/blob/3c7503cfb460457f88d400908ff2f5896f235d7c/renovate.json#L17-L20
